version: "3"

services:
  elasticsearch-node1:
    image: bitnami/elasticsearch:7.17.10
    ports:
      - '19200:9200'
      - '19300:9300'
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - './elasticsearch_node1_data:/bitnami'

  elasticsearch-node2:
    image: bitnami/elasticsearch:7.17.10
    ports:
      - '29200:9200'
      - '29300:9300'
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - './elasticsearch_node2_data:/bitnami'

  elasticsearch-node3:
    image: bitnami/elasticsearch:7.17.10
    ports:
      - '39200:9200'
      - '39300:9300'
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=1g
    volumes:
      - './elasticsearch_node3_data:/bitnami'

  kibana:
    image: bitnami/kibana:7.17.10
    ports:
      - "15601:5601"
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-node1
    volumes:
      - "./kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch-node1
      - elasticsearch-node2
      - elasticsearch-node3
