version: '3'

services:
  mysql-master:
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-master"
    hostname: "mysql-master.my-cluster"
    ports:
    - 13306:3306
    networks:
      mysql_net:
        ipv4_address: 172.16.111.10
        aliases:
        - "mysql-master.my-cluster"
    environment:
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_passw0rd
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/mysql-master.sql:/docker-entrypoint-initdb.d/mysql-master.sql
    - ./conf/mysql-master.cnf:/etc/mysql/conf.d/mysql-master.cnf
    - ./data/master:/var/lib/mysql
    - ./log/master:/var/log/mysql
  mysql-slave1:
    depends_on:
    - mysql-master
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-slave1"
    hostname: "mysql-slave1.my-cluster"
    ports:
    - 13307:3306
    networks:
      mysql_net:
        ipv4_address: 172.16.111.11
        aliases:
        - "mysql-slave1.my-cluster"
    environment:
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: my_passw0rd
      # MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/mysql-slave.sql:/docker-entrypoint-initdb.d/mysql-slave.sql
    - ./conf/mysql-slave1.cnf:/etc/mysql/conf.d/mysql-slave1.cnf
    - ./data/slave1:/var/lib/mysql
    - ./log/slave1:/var/log/mysql
  mysql-slave2:
    depends_on:
    - mysql-master
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-slave2"
    hostname: "mysql-slave2.my-cluster"
    ports:
    - 13308:3306
    networks:
      mysql_net:
        ipv4_address: 172.16.111.12
        aliases:
        - "mysql-slave2.my-cluster"
    environment:
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: my_passw0rd
      # MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/mysql-slave.sql:/docker-entrypoint-initdb.d/mysql-slave.sql
    - ./conf/mysql-slave2.cnf:/etc/mysql/conf.d/mysql-slave2.cnf
    - ./data/slave2:/var/lib/mysql
    - ./log/slave2:/var/log/mysql
  orchestrator:
    depends_on:
    - mysql-master
    restart: "always"
    image: openarkcode/orchestrator:v3.1.4
    container_name: "orchestrator"
    hostname: "orchestrator"
    networks:
      mysql_net:
        ipv4_address: 172.16.111.100
    ports:
    - 14000:3000
    volumes:
    - ./conf/orchestrator.conf.json:/etc/orchestrator.conf.json
  consul:
    restart: "always"
    image: consul:1.8
    container_name: consul
    hostname: consul
    networks:
      mysql_net:
        ipv4_address: 172.16.111.110
    ports:
    - 14001:8500
  consul-template:
    depends_on:
    - consul
    user: 0:0
    restart: "always"
    image: hashicorp/consul-template:alpine
    container_name: "consul-template"
    hostname: "consul-template"
    networks:
      mysql_net:
        ipv4_address: 172.16.111.120
    ports:
    - 3306:3306
    - 14002:8000
    volumes:
    - ./scripts/consul-template-start.sh:/consul-template/start.sh
    - ./conf/haproxy.cfg.ctmpl:/consul-template/data/haproxy.cfg.ctmpl
    command: /consul-template/start.sh
networks:
  mysql_net:
    ipam:
      driver: default
      config:
      - subnet: "172.16.111.0/24"
