version: '3'

services:
  mysql-master:
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-master"
    hostname: "mysql-master"
    ports:
    - 13306:3306
    networks:
      mysql-net:
        ipv4_address: 172.16.111.10
    environment:
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_passw0rd
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/master:/docker-entrypoint-initdb.d
    - ./conf/mysql-master.cnf:/etc/mysql/conf.d/mysql-master.cnf
    - ./data/master:/var/lib/mysql
    - ./log/master:/var/log/mysql
  mysql-slave1:
    depends_on:
    - mysql-master
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-slave1"
    hostname: "mysql-slave1"
    ports:
    - 13307:3306
    networks:
      mysql-net:
        ipv4_address: 172.16.111.11
    environment:
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: my_passw0rd
      # MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/slave:/docker-entrypoint-initdb.d
    - ./conf/mysql-slave1.cnf:/etc/mysql/conf.d/mysql-slave1.cnf
    - ./data/slave1:/var/lib/mysql
    - ./log/slave1:/var/log/mysql
    entrypoint:
    - bash
    - -c
    - |
      set -e
      echo 'Waiting for MySQL master to be available...'
      until ! mysql -h172.16.111.10 -urepl -prepl -e 'select 1;' | grep -q 1; do
        sleep 3
      done
      echo 'MySQL master has started.'
      docker-entrypoint.sh mysqld
  mysql-slave2:
    depends_on:
    - mysql-master
    restart: "always"
    image: mysql:8.0
    container_name: "mysql-slave2"
    hostname: "mysql-slave2"
    ports:
    - 13308:3306
    networks:
      mysql-net:
        ipv4_address: 172.16.111.12
    environment:
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: my_passw0rd
      # MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret_valley
    volumes:
    - ./scripts/slave:/docker-entrypoint-initdb.d
    - ./conf/mysql-slave2.cnf:/etc/mysql/conf.d/mysql-slave2.cnf
    - ./data/slave2:/var/lib/mysql
    - ./log/slave2:/var/log/mysql
    entrypoint:
    - bash
    - -c
    - |
      set -e
      echo 'Waiting for MySQL master to be available...'
      until ! mysql -hmysql-master -urepl -prepl -e 'select 1;' | grep -q 1; do
        sleep 3
      done
      echo 'MySQL master has started.'
      docker-entrypoint.sh mysqld

networks:
  mysql-net:
    ipam:
      driver: default
      config:
      - subnet: "172.16.111.0/24"
