version: '3'

services:
  zookeeper1:
    image: bitnami/zookeeper:3.5
    ports:
      - "12181:2181"
    volumes:
      - ./zookeeper1_data:/bitnami
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper2:
    image: bitnami/zookeeper:3.5
    ports:
      - "22181:2181"
    volumes:
      - ./zookeeper2_data:/bitnami
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
  zookeeper3:
    image: bitnami/zookeeper:3.5
    ports:
      - "32181:2181"
    volumes:
      - ./zookeeper3_data:/bitnami
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
