version: '3'

services:
  jenkins-1:
    restart: "always"
    image: jenkins/jenkins:lts-alpine
    container_name: "jenkins-1"
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      jenkins-net:
        ipv4_address: 172.16.111.101
    extra_hosts:
      - "updates.jenkins.io:172.16.111.100"
  jenkins-ng:
    restart: "always"
    image: nginx:1.20.0-alpine
    container_name: "jenkins-ng"
    volumes:
      - ./conf/jenkins-ng.conf:/etc/nginx/conf.d/jenkins-ng.conf
    networks:
      jenkins-net:
        ipv4_address: 172.16.111.100
networks:
  jenkins-net:
    ipam:
      driver: default
      config:
      - subnet: "172.16.111.0/24"
