version: '3'
services:
  mongodb-server:
    image: mongo:4.4
    container_name: "mongodb-server"
    restart: "always"
    ports:
    - 27017:27017
    networks:
      yapi-net:
        ipv4_address: 172.16.115.10
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: secret_valley
  yapi-server:
    depends_on:
    - mongodb-server
    image: jayfong/yapi:1.10.2
    container_name: "yapi-server"
    restart: always
    ports:
    - 13000:3000
    networks:
      yapi-net:
        ipv4_address: 172.16.115.11
    environment:
      YAPI_ADMIN_ACCOUNT: admin@docker.yapi
      YAPI_ADMIN_PASSWORD: adm1n
      YAPI_DB_SERVERNAME: mongodb-server
      YAPI_DB_PORT: 27017
      YAPI_DB_DATABASE: yapi
      #YAPI_DB_USER: root
      #YAPI_DB_PASS: secret_valley
networks:
  yapi-net:
    ipam:
      driver: default
      config:
      - subnet: "172.16.115.0/24"
