version: '3'

# See: https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/
# See: https://ververica.github.io/flink-cdc-connectors/master/content/quickstart/mysql-postgres-tutorial.html
services:
  flink-jobmanager:
    image: flink:1.16.2
    container_name: "flink-jobmanager"
    hostname: "flink-jobmanager"
    ports:
      - 6123:6123
      - 8081:8081
    networks:
      flink-net:
        ipv4_address: 172.16.112.10
    volumes:
      - ./lib/flink-sql-connector-mysql-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - ./lib/flink-sql-connector-elasticsearch7-1.16.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7-1.16.2.jar
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    command: "jobmanager"
  flink-taskmanager1:
    depends_on:
      - flink-jobmanager
    image: flink:1.16.2
    container_name: "flink-taskmanager1"
    hostname: "flink-taskmanager1"
    networks:
      flink-net:
        ipv4_address: 172.16.112.11
    volumes:
      - ./lib/flink-sql-connector-mysql-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - ./lib/flink-sql-connector-elasticsearch7-1.16.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7-1.16.2.jar
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    command: "taskmanager"
  flink-taskmanager2:
    depends_on:
      - flink-jobmanager
    image: flink:1.16.2
    container_name: "flink-taskmanager2"
    hostname: "flink-taskmanager2"
    networks:
      flink-net:
        ipv4_address: 172.16.112.12
    volumes:
      - ./lib/flink-sql-connector-mysql-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - ./lib/flink-sql-connector-elasticsearch7-1.16.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7-1.16.2.jar
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: flink-jobmanager"
    command: "taskmanager"
  # docker-compose run flink-sql-client
  flink-sql-client:
    depends_on:
      - flink-jobmanager
    image: flink:1.16.2
    container_name: "flink-sql-client"
    hostname: "flink-sql-client"
    networks:
      flink-net:
        ipv4_address: 172.16.112.13
    volumes:
      - ./lib/flink-sql-connector-mysql-cdc-2.3.0.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.3.0.jar
      - ./lib/flink-sql-connector-elasticsearch7-1.16.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7-1.16.2.jar
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        rest.address: flink-jobmanager
    command: bin/sql-client.sh
  # docker-compose exec flink-mysql mysql -uroot -P3306 -p123456
  flink-mysql:
    image: debezium/example-mysql:1.9
    container_name: "flink-mysql"
    hostname: "flink-mysql"
    ports:
      - "13306:3306"
    networks:
      flink-net:
        ipv4_address: 172.16.112.111
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpass
networks:
  flink-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.112.0/24"
